% Penicillin G production simulator ODE set
% This file is called by pensim2.m wrapper file
%
% I/O structure : dy = pengsimv1_6m(t,y,FLAG,inp1);
%
% Inputs:
% t: time span of integration
% y: initial conditions for that time span
% FLAG=[]; Matlab notation
% inp1: (1-by-14) vector of input parameters
%
% Output:
% dy: matrix of time stamps and ODE solutions
%
% Cenk Undey, Gulnur Birol and Ali Cinar (c) Control Group, February 01, 2000
% Illinois Institute of Technology, Chicago - IL/USA
%
% Acknowledgement: We gratefully acknowledge the ideas and insight of Dr. I. Birol on pH equilibrium equations.
%
% All rights reserved. Copyright (c) IIT 2002.


function dy=pengsimv1_6m(t,y,FLAG,inp1)
a=inp1(1);
F=inp1(2);
fgg=inp1(3);
pww=inp1(4);
Tf=inp1(5);
Fc=inp1(6);
b=inp1(7);
Fb=inp1(8);
Fa=inp1(9);
cab=inp1(10);
cb=inp1(11);
step1=inp1(12);
d1=inp1(13);
tfl=inp1(14);

sf=600;%substrate solution conc. g/L that is fed to the fermenter
a1=(1/0.45);% 1/(Yx/s)
a2=(1/0.9);% 1/(Yp/s)
a3=(1/0.04);% 1/(Yx/o)
a4=(1/0.2);% 1/(Yp/o)
a5=(1/7);% 1/k3 growth const. for penicillin
mx=0.014;% maintenance requirement of substrate
mo=0.467;% maintenance requirement of oxygen
mux=0.092;% max. specific growth rate
kx=0.15;% Contois saturation constant
mup=0.005;% max. specific rate of product formation
kp=0.0002;% Monod saturation constant
ki=0.1;%Substrate inhibition const. for product formation
mc=4e-7;%maintenance term for CO2
k4=1e-4;%penicillin biosynthesis const.
p=3;% exponent
k=0.04;% 1st order decay rate const. for product.
Ed=50000;%Activation energy for death 
kdd=1e33;%Arrhenius constant for death
Eg=5100;%Activation energy for growth
kdg=7e3;%Arrhenius constant for growth
ck=(1e-5);% mol H+/g biomass 
k1=1e-10;k2=7e-5;%constants for [H+]
rcp=(1/1500);% 1/(ro*cp) in 1/(cal/L.C) for the bulk in fermenter
rq1=60;% heat generated by fermentation in cal/g biomass
rq2=1.6783e-4;% heat generated by fermentation in cal/g biomass.h
a10=0.6;
Tc=290;%Cold water inlet temp.
Th=323;%Hot water inlet temp.

if b==1
   a9=8e5;
else
   a9=1e3;
end

clstar=a;

% Oxygen Limitation Decision
kox=2e-2*clstar*(1+tanh(50*(0.58-y(2))))/2;
kop=5e-4*(1+tanh(50*(0.58-y(2))))/2;

%y1=>S; %y2=>CL; %y3=>X; %y4=P %y5=V %y6=CO2 %y7=H %y8=T %y9=Qrxn
c1=y(1)/(kx*y(3)+y(1));
c2=y(2)/(kox*y(3)+y(2));
c3=y(1)/(kp+y(1)*(1+y(1)/ki));
c4=(y(2)^p)/(kop*y(3)+(y(2)^p));
c6=kdd*(exp(-Ed/(1.987*y(8))));
c7=kdg*(exp(-Eg/(1.987*y(8))));
c8=(1/(1+k1/y(7)+y(7)/k2));
c9=y(3)*(mux*c1*c2*c8*c7-F/y(5)-c6);
c5=rq1*c9*y(5)+rq2*y(3)*y(5);%Heat generated by fermentation in calories
c10=F+d1*Fb*cab/cb+d1*Fa*cab/cb-1e-4*y(5)*[exp(0.05*(y(8)-273))-1];% Volume correction
kla=70*sqrt(fgg)*((pww/y(5))^0.4);% fgg=inflow air rate, pww=agitator power
B=[(1e-14/y(7)-y(7))*y(5)-d1*cab*Fa*step1+d1*cab*Fb*step1]/(y(5)+d1*Fb*step1+d1*Fa*step1);

%---------ODEs-----
dy(1)=-y(3)*(mux*a1*c1*c2*c8*c7+mup*a2*c3*c4+mx-a1*c6)+F*sf/y(5)-y(1)*c10/y(5);

dy(2)=-y(3)*(mux*a3*c1*c2*c8*c7+mup*a4*c3*c4+mo-a3*c6)+kla*(clstar-y(2))-y(2)*F/y(5); 

dy(3)=c9;

dy(4)=mup*c3*c4*y(3)-k*y(4)-y(4)*F/y(5);

dy(5)=c10;

dy(6)=a5*y(3)*(mux*c1*c2*c8*c7-F/y(5)-c6+mc)+k4;

dy(7)=[ck*c9+[(-B+sqrt(B^2+4e-14))/2-y(7)]/step1];

dy(8)=rcp*y(9)/y(5)+F*(Tf-y(8))/y(5)-tfl*[((rcp/y(5))*a9*(Fc^(a10+1))*(y(8)-b*Th-(1-b)*Tc))/(Fc+(a9*(Fc^a10))/2000)];

dy(9)=c5;

dy=[dy(1);dy(2);dy(3);dy(4);dy(5);dy(6);dy(7);dy(8);dy(9)];
